### ISSUE TITLE
Solicitação de recurso: Inversão de Dependência na pasta "modules"

### ISSUE THREAD

**Issue by gsmatheus** [lss15/forge-chain-apps#1]
# Descrição
Gostaria de propor a implementação da inversão de dependência na pasta "modules" do projeto. Atualmente, o código em "modules" está altamente acoplado a implementações concretas, o que dificulta a manutenção, a testabilidade e a escalabilidade do projeto. A aplicação do princípio da inversão de dependência nos módulos traria diversos benefícios significativos.

## Vantagens da Inversão de Dependência

1. Desacoplamento: A inversão de dependência permite desacoplar os módulos de suas implementações concretas. Isso facilita a modificação, substituição e reutilização de componentes individuais, sem afetar todo o sistema.

2. Testabilidade: Com a inversão de dependência, é possível injetar facilmente dependências mockadas ou simuladas nos módulos durante os testes. Isso permite a criação de testes mais isolados, facilitando a identificação e correção de bugs.

3. Flexibilidade: Ao usar a inversão de dependência, é possível trocar facilmente as implementações dos módulos, seja para utilizar uma implementação diferente ou para adaptar o sistema a diferentes cenários. Isso traz flexibilidade e facilidade de evolução do sistema.

4. Reutilização: A inversão de dependência promove a reutilização de componentes, pois os módulos podem ser facilmente integrados a diferentes contextos, sem estarem acoplados a implementações específicas.

5. Organização: A aplicação da inversão de dependência na pasta "modules" ajudará a organizar o código, tornando-o mais legível e compreensível. A separação clara das responsabilidades e a explicitação das dependências facilitarão a manutenção e a colaboração no projeto.

## Justificativa

A aplicação da inversão de dependência na pasta "modules" é crucial para melhorar a arquitetura e a manutenibilidade do projeto. Ela promoverá um código mais modular, testável, flexível e organizado, resultando em um sistema mais robusto e sustentável a longo prazo.

**Comment by lss15** [comment]
Olá, muito obrigado pela sugestão. Gostaria de informar que implementei a inversão de dependência na pasta de módulos do projeto. Agora, estou utilizando a abordagem de inversão de dependência para melhorar a flexibilidade e a organização do código. Você pode conferir o commit [5821ce8](https://github.com/lss15/forge-chain-apps/commit/5821ce8ef1e2b0e8b15fcf14e8832a68bd2b6017) para mais detalhes sobre essa implementação. Agradeço novamente pela sua contribuição e peço que continue contribuindo!

**Comment by lss15** [comment]
Olá, muito obrigado pela sugestão. Gostaria de informar que implementei a inversão de dependência na pasta de módulos do projeto. Agora, estou utilizando a abordagem de inversão de dependência para melhorar a flexibilidade e a organização do código. Você pode conferir o commit [5821ce8](https://github.com/lss15/forge-chain-apps/commit/5821ce8ef1e2b0e8b15fcf14e8832a68bd2b6017) para mais detalhes sobre essa implementação. Agradeço novamente pela sua contribuição e peço que continue contribuindo!
